### ISSUE TITLE
using TextDecoder with hermes

### ISSUE THREAD

**Issue by davidliu** [facebook/hermes#1403]
## Problem

TextEncoder was recently added with 3863a36a53005dd1e6d39ea0d4ef5573bafde910 (related issue #948), but there doesn't seem to be a TextDecoder added. It seems odd that the encoder was added without the related decoder.

## Solution

Add TextDecoder to hermes.

**Comment by Badbird5907** [comment]
Hi, is this planned?

**Comment by tmikov** [comment]
It is planned, but not very high priority. PRs are welcome.

**Comment by gituser8796** [comment]
hi @tmikov is there a plan to release a TextDecoder?

**Comment by mabasic** [comment]
Having this issue in react-native 0.74. Workaround is to use import 'fast-text-encoder in every layout which uses an import which deals with TextDecoder.

Is there a fix for this in the near future?

**Comment by aretrace** [comment]
Eagerly awaiting for TextDecoder 🧘

**Comment by gituser8796** [comment]
hi @tmikov do we know when it will be in?

**Comment by heybuild** [comment]
I'm also waiting for this :/ Does anybody know how to find out which package depends on TextDecoder? I only get the error: ReferenceError: Property 'TextDecoder' doesn't exist, js engine: hermes
But I don't know where it comes from 😞

**Comment by aretrace** [comment]
@heybuild 
You have two options to polyfill the `TextDecoder` API:
- https://github.com/inexorabletash/text-encoding
- https://github.com/maksimlya/react-native-fast-encoder

I've written a short guide on how to use one of them to enable streaming in React Native (Expo):
👉  https://gist.github.com/aretrace/bcb0777c2cfd2b0b1d9dcfb805fe2838

**Comment by heybuild** [comment]
> @heybuild You have two options to polyfill the `TextDecoder` API:
> 
> * https://github.com/inexorabletash/text-encoding
> * https://github.com/maksimlya/react-native-fast-encoder
> 
> I've written a short guide on how to use one of them to enable streaming in React Native (Expo): 👉 https://gist.github.com/aretrace/bcb0777c2cfd2b0b1d9dcfb805fe2838

Thank you!
This did the trick:

```js
// index.ts
import "fast-text-encoding";
import "expo-router/entry";
```

**Comment by andy380743909** [comment]
> You have two options to polyfill the `TextDecoder` API:

Hi @aretrace ,
I have the same TextDecoder issue. When I use `TextDecoder('latin1')` in my ReactNative code, it causes error: Unknown encoding: latin1.
I tried to polyfill using [react-native-fast-encoder](https://github.com/maksimlya/react-native-fast-encoder) and `fast-text-encoding` in my App.ts, but it didn't work.

```
if (typeof global.TextEncoder === 'undefined') {
  global.TextEncoder = TextEncoder
}
if (typeof global.TextDecoder === 'undefined') {
  global.TextDecoder = TextDecoder
}
```

I did not use the TextDecode directly in my own code, it's a thirdparty library I dependent use TextDecode.
Should I modify the thirdparty library, do the polyfill?

**Comment by pranshuchittora** [comment]
Is there any working decoder polyfill for `latin1`?

I tried all of them and seeing this error `RangeError: Unknown encoding: latin1 (normalized: latin1), js engine: hermes`

**Comment by ChALkeR** [comment]
I just published [`@exodus/bytes@1.0.0-rc.9`](https://github.com/ExodusOSS/bytes)

It exposes:
```js
import { TextDecoder, TextEncoder } from '@exodus/bytes/encoding.js'
```

(You don't need `TextEncoder` though, as it's supported natively in Hermes)

It implements all encodings specified by https://encoding.spec.whatwg.org

It's 10-30x faster on Hermes than https://github.com/inexorabletash/text-encoding and 2x smaller
(main size component is the legacy multibyte encoding tables)

It passes WPT

**Comment by ChALkeR** [comment]
Also added `@exodus/bytes/encoding-lite.js` which omits legacy multi-byte encodings but is 9x smaller (or 18x smaller than `text-encoding`)

```js
import { TextDecoder, TextEncoder } from '@exodus/bytes/encoding-lite.js'
```

**Comment by brentforder** [comment]
@lavenzg This isn't fixed. I disabled my polyfill and I receive the following fatal error when my RN Expo app loads a service that uses h3-js:

` ERROR  [RangeError: Unknown encoding: utf-16le (normalized: utf-16le)]`

expo: 55.0.13
react-native: 0.83.4
h3-js: 4.4.0

My polyfill (loaded in index.ts):
`
import { polyfillGlobal } from 'react-native/Libraries/Utilities/PolyfillFunctions';
import { TextDecoder, TextEncoder } from 'fast-text-encoding';
if (__DEV__) {
  console.warn('Polyfilling TextDecoder & TextEncoder for Hermes');
};
polyfillGlobal("TextDecoder", () => TextDecoder);
polyfillGlobal("TextEncoder", () => TextEncoder);
`

**Comment by VadimCiv** [comment]
Hi is any solution for react-native Expo ? I upgraded to roslibjs v2

```
 ERROR  [RangeError: Unknown encoding: latin1 (normalized: latin1)] 

Code: init.ts
> 1 | import * as ROSLIB from 'roslib';
    | ^
  2 |
  3 | // Single ROS instance for the app
  4 | const ros = new ROSLIB.Ros({});
```

**Comment by tmikov** [comment]
@brentforder @VadimCiv do you have an actual Hermes problem with a repro to report?

**Comment by brentforder** [comment]
@tmikov Hermes has a lightweight / stripped-down TextDecoder that does not include support for the encoding type utf-16le. It's not a bug; this encoding type is simply missing.

Minimal repro: https://snack.expo.dev/@brentor/hermes-missing-encoding-for-h3
- Run the snack using the built-in iOS or Android simulator

It effectively means that the popular Uber H3 geospatial library (h3-js) is not compatible with RN / Hermes unless we polyfill Hermes with another TextDecoder.
What brings me back here to report it now is that recent RN versions now complain on every build about my usage of react-native/Libraries/Utilities/PolyfillFunctions to polyfill Hermes' TextDecoder.

**Comment by tmikov** [comment]
> [@tmikov](https://github.com/tmikov) Hermes has a lightweight / stripped-down TextDecoder that does not include support for the encoding type utf-16le. It's not a bug; this encoding type is simply missing.
> 
> Minimal repro: https://snack.expo.dev/@brentor/hermes-missing-encoding-for-h3
> 
> * Run the snack using the built-in iOS or Android simulator
> 
> It effectively means that the popular Uber H3 geospatial library (h3-js) is not compatible with RN / Hermes unless we polyfill Hermes with another TextDecoder. What brings me back here to report it now is that recent RN versions now complain on every build about my usage of react-native/Libraries/Utilities/PolyfillFunctions to polyfill Hermes' TextDecoder.

@brentforder your link is very far from a minimal repro - it pulls multiple dependencies, libraries that are not part of Hermes, requires a packager, etc. We cannot debug 3rd party libraries - that would not be a productive use of our time. If there is a Hermes problem, it needs to be reproduced without any dependencies.

The following would be a minimal repro, however it actually works, meaning that the problem must be something else:
```javascript
const bytes = new Uint8Array([0x48, 0x00, 0x69, 0x00, 0x21, 0x00]); // "Hi!" in UTF-16LE
const decoder = new TextDecoder('utf-16le');
console.log(decoder.decode(bytes)); // "Hi!"
```

**Comment by brentforder** [comment]
@tmikov apparently it only affects actual native builds. For web builds, RN is using the web browsers' TextDecoder rather than Hermes' TextDecoder, so there's no error. Try your same repro in an RN Android or RN iOS build and you'll see the same error I have.

I have no idea how to build for RN without Expo, but when I strip out everything I can from my sandbox example I see the described behavior. No error for web, and the error for Android or iOS.

https://snack.expo.dev/@brentor/hermes-missing-encoding-for-h3 (updated)

If you prefer another code sandbox that builds and simulates for Android/iOS without Expo, let me know.

**Comment by tmikov** [comment]
@brentforder can you provide a stack trace?

**Comment by jeanniton-mnr** [comment]
> > @heybuild You have two options to polyfill the `TextDecoder` API:
> > 
> > * https://github.com/inexorabletash/text-encoding
> > * https://github.com/maksimlya/react-native-fast-encoder
> > 
> > I've written a short guide on how to use one of them to enable streaming in React Native (Expo): 👉 https://gist.github.com/aretrace/bcb0777c2cfd2b0b1d9dcfb805fe2838
> 
> Thank you! This did the trick:
> 
> // index.ts
> import "fast-text-encoding";
> import "expo-router/entry";

Hello @heibuild 

Where did you place the code above?
