### ISSUE TITLE
Hermes based application crashes when trying to connect to the Flipper Hermes Debugger

### ISSUE THREAD

**Issue by Simek** [facebook/hermes#240]
Initially I was not sure where to report this issue, but I was directed here by @passy.

Currently when Hermes based application is running and I try to enter Hermes Debugger view in the Flipper the Android application crashes. There are some signs of working on the connection but after a brief while app is restarted. 

There is no problem with application until I click on the Hermes Debugger. React DevTools and other Flipper features are working as expected.

Screen capture showing the issue:
* https://streamable.com/77jg8q

Crash Tombstone file content (since there is no crash report):
* https://pastebin.com/X0HudGzM

Versions affected (at least I have tested this issue with the versions from ranges below): 
* RN: `0.62`-`0.63-rc.1`
* Flipper: `0.39`-`0.41`

**Comment by willholen** [comment]
@Simek This looks like an issue from 0.63-rc.0 that was fixed with https://github.com/facebook/react-native/commit/b645f23708c9d7eafb0fd40f0a33fa102b75bf15 in 0.63-rc.1.

According to your dump's build ids, you are using affected libraries from 0.63-rc.0.

You said that you've tested 0.63-rc.1, but could you please double check? Note in particular that the [0.63-rc.1 GitHub release notes](https://github.com/facebook/react-native/releases/tag/v0.63.0-rc.1) accidentally uses `-rc.0` in the command, so if you copy-pasted you may have gotten the wrong version.

If it still crashes in 0.63-rc.1 (where the build id for `x86/libfolly_json.so` is `42b1d93d8d42e56[...]`), please attach a tombstone file.

**Comment by Simek** [comment]
@willholen Thank you for the comprehensive answer!

My first report was in the late April so thats the reason for the `0.63-rc.0` in the tombstone. Crash persisted for me even on the `0.63-rc.1` to the time when I removed the `node_modules` and install all the dependencies again. After build on the clean installation of `0.63-rc.1` the issue do not persist anymore.

P.S. I have left message about wrong version in the React Native release post. I hope it will be fixed soon, thank you for bringing it up!
