### ISSUE TITLE
Cannot take heap snapshot in DevTools memory profiler: stuck at "Snapshotting..." after recording

### ISSUE THREAD

**Issue by SimpleCreations** [facebook/hermes#301]
## Bug Description

![ss+(2020-07-17+at+04 49 52)](https://user-images.githubusercontent.com/12449725/87793254-ad139480-c84d-11ea-8e45-a20a4ca605a4.png)

There are no errors in the console and the app is fully responsive. The console is working too.

Chrome version: 84.0.4147.89
Hermes version: 0.4.2-rc1
React Native version (if any): 0.62.2
Android version (if any): 10
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64): arm64-v8a

**Comment by dulinriley** [comment]
Thanks for reporting this, I've been able to reproduce the problem locally. In the case I'm seeing, Hermes is crashing while preparing the snapshot JSON blob to send back to Chrome. Unfortunately I only have a partially symbolicated stack trace.

I'll need to build Hermes from source in order to debug this, which is a complicated setup. So it might take me a few days to put up some fixes.

**Comment by dulinriley** [comment]
@SimpleCreations I haven't been able to make a source build to track down this assertion yet (Gradle seems to either be ignoring my changes, or there's an ABI difference causing insta segfaults).

However, I remembered I fixed an issue that might have been the cause of this a couple months ago: https://github.com/facebook/hermes/commit/4c468bc9e0cf61614c62f4fe6d9b09a427362a07

It's possible that commit will fix your issue; unfortunately, it hasn't been part of a release yet so it's not easy to test. I believe there will be a Hermes v0.6.0 release soon which will include that commit and be part of the React Native 0.64.X release.

**Comment by AndrewMorsillo** [comment]
Can confirm that this still doesn't work on `0.5.2-rc1`. CPU profile just hangs on "loading" until you delete it. Heap dump crashes Hermes.

**Comment by dulinriley** [comment]
The commit which should fix this is in Hermes v0.6.0 and v0.7.0. Those will be deployed with RN v0.64, which should be releasing any day now. This isn't added to any of the v0.5.* releases, or v0.4.*

@AndrewMorsillo you mention "CPU profile". This issue (and my fix) were for a different issue in taking heap snapshots. What button did you press to take a CPU Profile? I don't think Hermes supports any of the Chrome CPU profilers currently.

You can open a separate issue with more details about the CPU profiler, and we can make the issue about adding support for that.

**Comment by dulinriley** [comment]
Going to close this as RN 0.64 is coming out soon with the fixes to these.
Please re-open if RN 0.64 is still having trouble taking heap snapshots.

**Comment by chanphiromsok** [comment]
still exist in react-native 0.73

![Screenshot 2024-06-07 at 11 29 14](https://github.com/facebook/hermes/assets/65760336/d0380412-0ef1-428a-a2f3-607bb19c6854)

**Comment by mattbfb** [comment]
@chanphiromsok Thanks for reporting this. This is a new behavior in recent versions of Chrome. We have submitted a fix that will be available in future versions of Hermes and React Native.

In the meantime, you should be able to restore the previous behavior by using an older version of Chrome DevTools. You can do this by installing a previous version of Chrome/Chrome Canary. Alternatively, you may be able to use use a hosted version of Chome DevTools, e.g. https://chrome-devtools-frontend.appspot.com/serve_file/@60127beb442528082b3f6eff7392267e145262c3/js_app.html?ws=127.0.0.1%3A8081 while your application is running and connected to Metro.
