### ISSUE TITLE
Some date formats that worked in JSC fail with Hermes

### ISSUE THREAD

**Issue by luizsn000** [facebook/hermes#647]
## Bug Description

When using dates like on the web, for example: 11/30/2000 00:00:00 I get "Invalid Date"

- [x] I have run `gradle clean` and confirmed this bug does not occur with JSC

Hermes version: 0.9.0
React Native version (if any): 0.66.1
OS version (if any):
Platform (most likely one of arm64-v8a, armeabi-v7a, x86, x86_64):

## Steps To Reproduce

1. Pass the format '11/30/2021 00:00:00" in the Javascript Date Builder
2. Show result on console

## More infos

I tried to rewrite the Date constructor but I get the following message: RangeError: "Date value out of bounds, js engine: hermes"

**Comment by neildhar** [comment]
Hi @luizsn000, could you share a little more about the version of V8 that this work on, and the command you're using? I get an invalid date with the given string on both V8 and JSC:

JSC:
```
neildhar@neildhar-mbp ~/f/x/m/hermes (default) > ~/.jsvu/javascriptcore
>>> new Date("30/11/2021 00:00:00")
Invalid Date
```

V8:
```
neildhar@neildhar-mbp ~/f/x/m/hermes (default)> ~/.jsvu/v8
V8 version 8.7.75
d8> new Date("30/11/2021 00:00:00")
Invalid Date
```

**Comment by luizsn000** [comment]
> Hi @luizsn000, could you share a little more about the version of V8 that this work on, and the command you're using? I get an invalid date with the given string on both V8 and JSC:
> 
> JSC:
> 
> ```
> neildhar@neildhar-mbp ~/f/x/m/hermes (default) > ~/.jsvu/javascriptcore
> >>> new Date("30/11/2021 00:00:00")
> Invalid Date
> ```
> 
> V8:
> 
> ```
> neildhar@neildhar-mbp ~/f/x/m/hermes (default)> ~/.jsvu/v8
> V8 version 8.7.75
> d8> new Date("30/11/2021 00:00:00")
> Invalid Date
> ```

I noticed my error and edited the issue description. Date format for playback is MM/DD/YYYY hh:mm:ss

**Comment by neildhar** [comment]
I see that both V8 and JSC support this format, so thank you for reporting it. The spec only outlines a date format based on ISO 8601, so using ISO dates is the best way to get consistent behaviour across JS engines. That said, since this is something that other engines support consistently, we should consider adding it.

**Comment by luizsn000** [comment]
How can I request the addition of the format in Hermes?

**Comment by neildhar** [comment]
We'll keep this issue open to track the request.

**Comment by tmikov** [comment]
What is the use case for this, since the Date constructor really can't be used reliably to parse arbitrary dates?

**Comment by crutchcorn** [comment]
@luizsn000, please reopen this ticket - as it's not resolved yet.

If you'd like to avoid getting notifications, you can do so on the sidebar, like so

<img width="326" alt="image" src="https://user-images.githubusercontent.com/9100169/205701170-f109b42b-ec0c-4efc-875a-ee0d773c201c.png">

**Comment by nios87** [comment]
We are in the same boat. Api returns the date in that format and that is what currently stops us from switching hermes on.

**Comment by bryanltobing** [comment]
return `invalid date` for me on ios

**Comment by ucheNkadiCode** [comment]
Yes this is the exact issue I also have. Really would love to use Hermes. I’m using 

new Date().toJson() to create isostring dates but when I pull in the values into my application I get invalid date format

**Comment by vksgautam1986** [comment]
can we have any work around for this , its preventing us from using hermas in 0.72

**Comment by tmikov** [comment]
We are looking into this and will implement a fix in Hermes. We are trying to understand why this is format is considered valid by other engines - Month/Day/Year is very US-centric and doesn't make sense in Europe. 

I am also curious to understand the use case for this rather illogical format. Which APIs return non-localized date strings in US format? Isn't that a bug in those APIs? 

To be clear, we will match what other engines are doing, but I am trying to better understand the root of the problem.

**Comment by andrewdazs** [comment]
I've just updated the RN version from 65 to 72 with Hermes enabled and I'm getting the same error message.

`[RangeError: Date value out of bounds]`

I'm just using dates in this format `YYYY-MM-DD`

Any update on this?

**Comment by tmikov** [comment]
@andrewdazs I just tried `new Date("2023-12-13")` and it is working as expected. Can you share an example that is causing the error for you?

**Comment by andrewdazs** [comment]
What's causing the error is when I use `.toISOString()` to format the date.

Example: `new Date("2023-12-12").toISOString()`

@tmikov could you try to reproduce with this example?

**Comment by tmikov** [comment]
@andrewdazs I tried it and I don't see an error. Does the error reproduce for you in the Hermes CLI tool?

**Comment by leogersen** [comment]
> What's causing the error is when I use `.toISOString()` to format the date.
> 
> Example: `new Date("2023-12-12").toISOString()`
> 
> @tmikov could you try to reproduce with this example?

I'm having exactly the same error, for the same situation:

This started when i upgrade to react-native 0.72.6

**Comment by tmikov** [comment]
@leogersen As I said above, I am unable to reproduce this error. Are you seeing the error on iOS or Android?

Can you please try the Hermes CLI tool of your version as well as the CLI tool of the latest Hermes version.

**Comment by andrewdazs** [comment]
I discovered that at some point of my code I was sending NaN to `toISOString()` and this was causing the error. If I see this error again I'll try to look into it in depth.

**Comment by tmikov** [comment]
@luizsn000 I don't think we have addressed this yet?

**Comment by schonarth** [comment]
No, not yet. I'm reverting to JSC on my project as I just found that my date-related bugs are due to Hermes handling them differently and will happily switch back once this has been fixed :)

**Comment by titanve** [comment]
Hey all!

I'm still getting the error:
![image](https://github.com/facebook/hermes/assets/4803351/6511a4f9-d85c-46b0-8c8d-8b4b7d191dbb)

**Comment by titanve** [comment]
I had to use this approach:

```
if (hini instanceof Date && !isNaN(hini) && hfin instanceof Date && !isNaN(hfin)) {
  ...
}
```

**Comment by hglt1998** [comment]
I really need help with this issue, any approach to a stable solution??

**Comment by Grohden** [comment]
Get the same with `new Date('July 30, 2022').toISOString()`, which worked in JSC (` 2022-07-30T03:00:00.000Z`) but breaks in hermes (`RangeError: Date value out of bounds, js engine: hermes`)

**Comment by tmikov** [comment]
@Grohden do you mind submitting a separate issue for this format. Also, can you please link to a formal description of the expected semantics, since this format is not described in ECMAScript, as far as I can tell.

**Comment by wojtekmaj** [comment]
This is still an issue in 0.84 with Hermes V1 enabled by default.

Unfortunately the only way around this is to parse the dates yourself to an ISO-like format and parse *that* as a Date.
